# Generated by Django 5.0.2 on 2024-02-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ident', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('cel', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('adrress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wine_letter',
            fields=[
                ('id_wine', models.AutoField(primary_key=True, serialize=False)),
                ('wine_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('yaer', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.person')),
                ('prod', models.ManyToManyField(to='page.wine_letter')),
            ],
        ),
    ]
